workspace:
  base: /go
  path: src/github.com/umputun/secrets

pipeline:
  
  build:
    image: golang:1.9-alpine
    commands:
      - cd app
      - go build -v ./...

  docker:
    image: plugins/docker
    repo: umputun/secrets
    secrets: [ docker_username, docker_password ]
    tags: 
      - ${DRONE_COMMIT_BRANCH/\//-}
    when:
      event: push

  pr_build:
    image: docker
    commands:
      - docker build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: pull

  deploy:
    image: appleboy/drone-ssh
    host: safesecret.info
    username: umputun
    port: 22
    secrets: [ ssh_key ]
    script:
      - cd /srv/secrets
      - docker-compose pull
      - docker-compose up -d
    when:
      branch: master
      event: push

  notify:
    image: drillster/drone-email
    host: smtp.mailgun.org
    port: 25
    username: email_username
    password: email_password
    from: drone@mg.umputun.com
    recipients: [ umputun@gmail.com ]
    secrets: [ email_username, email_password ]
    when:
      status: [ changed, failure ]
